### ISSUE TITLE
Adding Harmony activity volume as volume_entity

### ISSUE THREAD

**Issue by colfin22** [sbryfcz/harmony-card#1]
Many thanks for this, I'm only installing so am still getting my head around it and configuring

Is it possible? I have 3 activiities, they use different sound devices, one uses the TV, another uses my surround receiver, and a third just uses the TV speakers

**Comment by sbryfcz** [comment]
Interesting! Any thoughts on what the configuration might look like? Maybe we can work up an example configuration yaml? 

Something like:
```yaml
- type: 'custom:harmony-card'
  entity: remote.living_room_hub # the harmony entity
  volume_entity: media_player.living_room # make this optional? This allows for a volume slider
  volume_device: # make this an option harmony device to use for all activities unless specified in activity?
  activities:
  - name: Play Xbox One
     device: Microsoft Xbox One
     volume_device: # optional device to use for this activity
  - name: Listen to Music
     device: Onkyo AV Receiver
     volume_device: # optional device to use for this activity
```

Let's iterate on this a bit and then I likely can make some quick updates.
