### ISSUE TITLE
Center button on remote doesn't select/enter/ok

### ISSUE THREAD

**Issue by nikiyao** [sbryfcz/harmony-card#3]
Center button on remote doesn't select/enter/ok I can navigate the screen with the arrow buttons but the center button does nothing. Device is a Sony Bravia tv.

**Comment by nikiyao** [comment]
This is the error that shows up in my logs

Log Details (ERROR)
Sun Feb 02 2020 12:16:13 GMT-0500 (Eastern Standard Time)
Sending command OK to device 59037218 failed with code 566: Command not found for device id:59037218

**Comment by sbryfcz** [comment]
Thanks. I'm going to take a look at this. I may have to make it so that you can specify the button commands in the configuration. I'm thinking of using key-value pairs of the form "button":"command"?

I'm thinking the configuration could look something like this:

```yaml
- type: 'custom:harmony-card'
  entity: remote.living_room_hub
  activities:
  - name: Watch TV
    device: Sony Bravia tv
    buttons:
    - dpad-center: Enter
```

You will need to look at your harmony .conf file under configuration to learn what the appropriate command needs to be. It doesn't seem like the Harmony API has a clean way to automatically identify that, and I'd rather make it configurable for all users.

And I'd publish a list of all the buttons/commands for this card.

Thoughts?
