### ISSUE TITLE
Hide/ Replace XBox buttons

### ISSUE THREAD

**Issue by Kanishkaz** [sbryfcz/harmony-card#4]
Hi,
Just installed your card and it looks great.
I don't have a Xbox. Is it possible to hide the Xbox related buttons or replace them?
Thanks.

**Comment by sbryfcz** [comment]
Good suggestion, I'll try to add some more configuration about hiding/showing different aspects of the card.

**Comment by sbryfcz** [comment]
So I'm thinking configuration to perform this sort of configuration could look something like:

```yaml
- type: 'custom:harmony-card'
  entity: remote.living_room_hub
  activities:
  - name: Watch TV
    device: Sony Bravia tv
hide:
    - xbox: true
    - a: true
    - b: true
    - x: true
    - y: true 
```

This sort of configurability is similar to the [mini media player card](https://github.com/kalkih/mini-media-player#hide-object)....which I love! 

Open to suggestions.

Thoughts?
