### ISSUE TITLE
Using volume_entity at activity level does not override card volume_entity as per order of precedence

### ISSUE THREAD

**Issue by kalhimeo** [sbryfcz/harmony-card#46]
Dear developer,

I experience a bug with the volume control of the harmony card. I have a very basic setup : One card to switch between 2 activities and control the volume of one of them via 'volume_entity' (Marantz media player).

```
type: 'custom:harmony-card'
entity: remote.salon
tap_action: none
activities:
  - device: Console de jeu NVIDIA
    name: Télévision
    volume_entity: media_player.marantz_sr5011
  - device: Ampli Marantz
    name: Musique`
```

With this configuration, the volume of the Marantz receiver is correctly displayed, but any change from the card would not be applied (neither mute, slider, or volume up/down).

If I change my config and add the volume_entity on the "card level" in addition of the "activity level", the volume selection is working fine from the card.

Could you please have a look ?

Thank you very much !
