### ISSUE TITLE
Feature: Buttons linked to a activities

### ISSUE THREAD

**Issue by poudenes** [sbryfcz/harmony-card#51]
Hi There,

Nice AddOn!!!

Would be nice to link all the buttons to different activities , like example below:

```
activities:
  - name: Kodi
    device: Kodi
  - name: AppleTV
    device: AppleTV

buttons:
  default:
    a:
      icon: 'mdi:chevron-up'
      device: Device1
      command: VolumeUp
    b:
      icon: 'mdi:chevron-down'
      device: Device1
      command: VolumeDown

  Kodi:
    a:
      icon: 'mdi:chevron-up'
      device: Device1
      command: VolumeUp
    b:
      icon: 'mdi:chevron-down'
      device: Device1
      command: VolumeDown

  AppleTV:
    a:
      icon: 'mdi:chevron-up'
      device: Device2
      command: VolumeUp
    b:
      icon: 'mdi:chevron-down'
      device: Device2
      command: VolumeDown
```

So when activity "Kodi" is active, then use the buttons: button>Kodi.
When other activity is active then use the buttons that belong to the activity.
When there is no specific button config then always use default

Cheers

**Comment by N1c093** [comment]
Do you mean, that you want to change the buttons based on the current/active activity? 

This is already possible. In the following example I change the buttons "a" & "b" if the activity "Fernsehen" is active.

Example:
```yaml

activities:
  - name: Fernsehen
    volume_device: Sony TV
    device: Sony TV
    hide_keyPad: false
    buttons:
      a:
        color: null
        command: ChannelDown
        device: Sony TV
        hide: false
        icon: 'mdi:chevron-down'
      b:
        color: null
        command: ChannelUp
        device: Sony TV
        hide: false
        icon: 'mdi:chevron-up'
```
