### ISSUE TITLE
Hide of volume buttons not possible

### ISSUE THREAD

**Issue by werfpsa** [sbryfcz/harmony-card#52]
It works for all the buttons. You can hide them for the current activity.
I would like to hide all buttons for activity 'PowerOff'. It works well, except for the volume bar (volume_down, volume_up, volume_mute).
Would be great if this can be fixed.

**Comment by werfpsa** [comment]
my card configuration PowerOff:
  - buttons:
      back:
        hide: true
      dpad_audio:
        hide: true
      dpad_center:
        hide: true
      dpad_menu:
        hide: true
      dpad_option:
        hide: true
      dpad_info:
        hide: true
      dpad_sub:
        hide: true
      dpad_tmenu:
        hide: true
      dpad_up:
        hide: true
      dpad_down:
        hide: true
      dpad_left:
        hide: true
      dpad_right:
        hide: true
      play:
        hide: true
      pause:
        hide: true
      volume_down:
        hide: true
      volume_up:
        hide: true
      volume_mute:
        hide: true
      skip_back:
        hide: true
      skip_forward:
        hide: true
      xbox:
        hide: true
      a:
        hide: true
      b:
        hide: true
      x:
        hide: true
      'y':
        hide: true
    name: PowerOff
    icon: 'mdi:power-standby'
    device: DENON AVC-8500 Main Zone

**Comment by werfpsa** [comment]
I have 6 extra buttons (menu, option, info, etc)

**Comment by N1c093** [comment]
Why do you have an additional action defined for "PowerOff"?
I think you won't need it. The button "OFF" it generated automatically.

Here you can see my configuration: 

```yaml
entity: remote.wohnzimmer
activities:

  - name: Fernsehen
    volume_device: Sony TV
    device: Sony TV
    hide_keyPad: false
    buttons:
      a:
        color: null
        command: ChannelDown
        device: Sony TV
        hide: false
        icon: 'mdi:chevron-down'
      b:
        color: null
        command: ChannelUp
        device: Sony TV
        hide: false
        icon: 'mdi:chevron-up'

    
  - name: Fire TV sehen
    volume_device: Onkyo AV-Empfänger
    device: Amazon Fire TV
    buttons:
      a:
        color: null
        command: Home
        device: Amazon Fire TV
        hide: false
        icon: 'mdi:home'
      dpad_up:
        hide: false
      dpad_down:
        hide: false
      dpad_left:
        hide: false
      dpad_right:
        hide: false
      dpad_center:
        hide: false
      back:
        hide: false
      play:
        hide: false
      pause:
        hide: false
      skip_forward:
        hide: false
      skip_back:
        hide: false

  - name: Spotify Wohnzimmer
    volume_device: Onkyo AV-Empfänger
    device: Onkyo AV-Empfänger
    buttons:
      play:
        hide: false
      pause:
        hide: false
      skip_forward:
        hide: false
      skip_back:
        hide: false

buttons:
  a:
    hide: true
  b:
    hide: true
  x:
    hide: true
  xbox:
    hide: true
  'y':
    hide: true
  dpad_up:
    hide: true
  dpad_down:
    hide: true
  dpad_left:
    hide: true
  dpad_right:
    hide: true
  dpad_center:
    hide: true
  back:
    hide: true
  play:
    hide: true
  pause:
    hide: true
  skip_forward:
    hide: true
  skip_back:
    hide: true

type: 'custom:harmony-card'

```

Can you share your complete configuration and also use code highlighting/quoting? It's hard to read without code-highlighting.


\```yaml
YOUR CONFIG
\```

**Comment by werfpsa** [comment]
I have defined an extra button for PowerOff to avoid many hide: false for every of the activities (I use a lot of activities and buttons). The only buttons I cannot hide are the volume onces. I have tested with your approach and still the volume buttons are not hided.

```yaml
activities:
  - buttons:
      back:
        color: '#ffdacb'
        command: Back
        icon: 'mdi:undo-variant'
      dpad_audio:
        command: Guide
        icon: 'mdi:television-guide'
      dpad_center:
        command: OK
      dpad_menu:
        command: Menu
      dpad_option:
        command: Options
      dpad_tmenu:
        command: TV
        icon: 'mdi:television'
      skip_back:
        command: ChannelPrev
      skip_forward:
        command: ChannelDown
      xbox:
        command: Home
        icon: 'mdi:home'
    device: Philips 55OLED803
    name: TV kijken
    icon: 'mdi:television-box'
    hide_keyPad: false
    volume_entity: media_player.denon_avc_x8500h_2
  - buttons:
      a:
        command: Stop
        device: OPPO UDP-203
        icon: 'mdi:stop'
      dpad_audio:
        command: Audio
      dpad_center:
        command: Enter
      dpad_menu:
        command: Pop-UpMenu
      dpad_option:
        command: Option
      dpad_tmenu:
        command: TopMenu
      skip_back:
        command: ChapterPrev
      skip_forward:
        command: ChapterNext
      xbox:
        command: Home
        icon: 'mdi:home'
    device: OPPO UDP-203
    name: Oppo TV
    icon: 'mdi:disc-player'
    volume_entity: media_player.denon_avc_x8500h_2
  - buttons:
      a:
        command: Stop
        device: OPPO UDP-203
        icon: 'mdi:stop'
      dpad_audio:
        command: Audio
      dpad_center:
        command: Enter
      dpad_menu:
        command: Pop-UpMenu
      dpad_option:
        command: Option
      dpad_tmenu:
        command: TopMenu
      skip_back:
        command: ChapterPrev
      skip_forward:
        command: ChapterNext
      xbox:
        command: Home
        icon: 'mdi:home'
    device: OPPO UDP-203
    name: Oppo app
    icon: 'mdi:ipod'
    volume_entity: media_player.denon_avc_x8500h_2
  - buttons:
      back:
        command: Back
      dpad_audio:
        hide: true
      dpad_center:
        command: Select
      dpad_menu:
        command: Menu
      dpad_option:
        hide: true
      dpad_tmenu:
        hide: true
      skip_back:
        command: SkipBack
      skip_forward:
        command: SkipForward
      xbox:
        command: Menu
        icon: 'mdi:silverware'
    device: Tv Apple 4K
    icon: 'mdi:apple'
    name: Apple TV
    volume_entity: media_player.denon_avc_x8500h_2
  - buttons:
      back:
        command: Exit
        icon: 'mdi:exit-to-app'
      dpad_audio:
        hide: true
      dpad_center:
        command: OK
      dpad_menu:
        hide: true
      dpad_option:
        hide: true
      dpad_tmenu:
        hide: true
      skip_back:
        command: PreviousTrack
      skip_forward:
        command: NextTrack
      xbox:
        command: Info
        icon: 'mdi:information'
    device: Naim SuperUniti
    name: Naim
    icon: 'mdi:surround-sound-2-0'
    volume_entity: media_player.naim_superuniti
  - buttons:
      back:
        command: Exit
        icon: 'mdi:exit-to-app'
      dpad_center:
        command: Select
      skip_back:
        command: ChapterPrev
      skip_forward:
        command: ChapterNext
      xbox:
        command: Menu
        icon: 'mdi:silverware'
    device: T+A SACD
    name: T&A CD
    icon: 'mdi:disc'
    volume_entity: media_player.naim_superuniti
  - buttons:
      back:
        command: Back
      dpad_audio:
        hide: true
      dpad_center:
        command: Select
      dpad_menu:
        command: Menu
      dpad_option:
        command: Option
      dpad_tmenu:
        hide: true
      skip_back:
        command: SkipBack
      skip_forward:
        command: SkipForward
      xbox:
        hide: true
    device: DENON AVC-8500 Main Zone
    name: HEOS
    icon: 'mdi:music-box-multiple'
    volume_entity: media_player.denon_avc_x8500h_2
  - buttons:
      back:
        command: Return
      dpad_audio:
        hide: true
      dpad_center:
        command: Enter
      dpad_menu:
        command: PopUpMenu
      dpad_option:
        hide: true
      dpad_tmenu:
        command: TopMenu
      skip_back:
        command: ChapterPrev
      skip_forward:
        command: ChapterNext
      xbox:
        command: TopMenu
    device: Dune HD solo Lite
    icon: 'mdi:play-network'
    name: Dune TV
    volume_entity: media_player.denon_avc_x8500h_2
  - buttons:
      back:
        hide: true
      dpad_audio:
        hide: true
      dpad_center:
        hide: true
      dpad_menu:
        hide: true
      dpad_option:
        hide: true
      dpad_info:
        hide: true
      dpad_sub:
        hide: true
      dpad_tmenu:
        hide: true
      dpad_up:
        hide: true
      dpad_down:
        hide: true
      dpad_left:
        hide: true
      dpad_right:
        hide: true
      play:
        hide: true
      pause:
        hide: true
      volume_down:
        hide: true
      volume_up:
        hide: true
      volume_mute:
        hide: true
      skip_back:
        hide: true
      skip_forward:
        hide: true
      xbox:
        hide: true
      a:
        hide: true
      b:
        hide: true
      x:
        hide: true
      'y':
        hide: true
    name: PowerOff
    icon: 'mdi:power-standby'
buttons:
  a:
    color: '#e43308'
    command: Red
    device: Philips 55OLED803
    icon: 'mdi:alpha-z-circle'
  b:
    color: '#2d9f1c'
    command: ModeMovie
    device: DENON AVC-8500 Main Zone
    icon: 'mdi:alpha-v-circle'
  back:
    color: '#ffdacb'
    command: Return
    icon: 'mdi:undo-variant'
  dpad_audio:
    color: '#40e0d0'
  dpad_info:
    color: '#40e0d0'
  dpad_menu:
    color: '#40e0d0'
  dpad_option:
    color: '#40e0d0'
  dpad_sub:
    color: '#40e0d0'
  dpad_tmenu:
    color: '#40e0d0'
  x:
    color: '#003bbd'
    command: ModeMusic
    device: DENON AVC-8500 Main Zone
    icon: 'mdi:alpha-m-circle'
  xbox:
    color: '#fd7435'
    command: Home
    icon: 'mdi:home'
  'y':
    color: '#f1c70f'
    command: ModePure
    device: DENON AVC-8500 Main Zone
    icon: 'mdi:alpha-p-circle'
entity: remote.woonkamer
hide_keyPad: true
show_activities_icons: true
hide_activities: false
scale: 1.5
style: |
  ha-card {
    font-variant: small-caps;
  }
type: 'custom:harmony-card'
volume_device: DENON AVC-8500 Main Zone
volume_entity: media_player.denon_avc_x8500h_2

```

**Comment by N1c093** [comment]
Okay, I think I found a workaround for your problem.
You have to specify an "volume_device" in your activity "PowerOff".
I already made this modification down below.

Anyway I don't know if this additional activity "PowerOFF" will make any other problems in the future. 

It would be great if there will be an configuration-option in harmony-card to hide all buttons if activity is "OFF". Hopefully they will add this options in the future.

```yaml

  - buttons:
      back:
        hide: true
      dpad_audio:
        hide: true
      dpad_center:
        hide: true
      dpad_menu:
        hide: true
      dpad_option:
        hide: true
      dpad_info:
        hide: true
      dpad_sub:
        hide: true
      dpad_tmenu:
        hide: true
      dpad_up:
        hide: true
      dpad_down:
        hide: true
      dpad_left:
        hide: true
      dpad_right:
        hide: true
      play:
        hide: true
      pause:
        hide: true
      volume_down:
        hide: true
      volume_up:
        hide: true
      volume_mute:
        hide: true
      skip_back:
        hide: true
      skip_forward:
        hide: true
      xbox:
        hide: true
      a:
        hide: true
      b:
        hide: true
      x:
        hide: true
      'y':
        hide: true
    name: PowerOff
    volume_device: DENON AVC-8500 Main Zone
    icon: 'mdi:power-standby'

```
