### ISSUE TITLE
Feature Request: Hide all buttons if activity is off

### ISSUE THREAD

**Issue by N1c093** [sbryfcz/harmony-card#53]
First of all thank you for your great work 👍 

I think it would be great, if a new configuration option will be added to hide all buttons if the current activity is "off/poweroff". Maybe you can name it `hide_buttons_poweroff`

Currently you have to hide each of the buttons manually in the "general options" and re-enable each of them in the "activity option"  if you need one of the button. This results in a really long config.

I hope you understand what I mean. Thanks in advance.

**Comment by McDAlexander** [comment]
For anyone that wants an alternative workaround to setting up a powered off activity, I setup [state-switch](https://github.com/thomasloven/lovelace-state-switch) to adjust the buttons when on vs off. Here's an example of one of my harmony hubs.
```
type: 'custom:state-switch'
entity: remote.living_room_hub
states:
  'on':
    name: Living Room TV
    entity: remote.living_room_hub
    volume_device: Vizio TV
    scale: 1.5
    show_activities_icons: true
    activities:
      - name: Livingroom SHIELD TV
        device: NVIDIA Game Console
        icon: 'mdi:television-play'
        buttons:
          dpad_center:
            icon: 'mdi:checkbox-blank-circle'
            device: NVIDIA Game Console
            command: Select
          xbox:
            hide: true
          a:
            hide: true
          b:
            hide: true
          x:
            hide: true
          'y':
            hide: true
      - name: Play Nintendo Switch
        device: Nintendo Game Console
        icon: 'mdi:nintendo-switch'
        buttons:
          xbox:
            hide: true
          a:
            hide: true
          b:
            hide: true
          x:
            hide: true
          'y':
            hide: true
      - name: Play Xbox One
        device: Microsoft Game Console
        icon: 'mdi:microsoft-xbox'
      - name: Listen to Music
        device: Vizio Amp
        icon: 'mdi:music-note'
        volume_device: Vizio Amp
        buttons:
          xbox:
            hide: true
          a:
            hide: true
          b:
            hide: true
          x:
            hide: true
          'y':
            hide: true
    type: 'custom:harmony-card'
  'off':
    name: Living Room TV
    entity: remote.living_room_hub
    volume_device: Vizio TV
    scale: 1.5
    show_activities_icons: true
    activities:
      - name: Livingroom SHIELD TV
        device: NVIDIA Game Console
        icon: 'mdi:television-play'
      - name: Play Nintendo Switch
        device: Nintendo Game Console
        icon: 'mdi:nintendo-switch'
      - name: Play Xbox One
        device: Microsoft Game Console
        icon: 'mdi:microsoft-xbox'
      - name: Listen to Music
        device: Vizio Amp
        icon: 'mdi:music-note'
        volume_device: Vizio Amp
    buttons:
      volume_down:
        hide: true
      volume_up:
        hide: true
      volume_mute:
        hide: true
      skip_back:
        hide: true
      play:
        hide: true
      pause:
        hide: true
      skip_forward:
        hide: true
      dpad_up:
        hide: true
      dpad_down:
        hide: true
      dpad_left:
        hide: true
      dpad_right:
        hide: true
      dpad_center:
        hide: true
      xbox:
        hide: true
      back:
        hide: true
      a:
        hide: true
      b:
        hide: true
      x:
        hide: true
      'y':
        hide: true
    type: 'custom:harmony-card'
```
