### ISSUE TITLE
Hide all control buttons when Harmony Hub is off

### ISSUE THREAD

**Issue by Snuffy2** [sbryfcz/harmony-card#63]
Just installed and everything is working well. Great job! I was wondering if there was any way to set it to hide all of the buttons except the Activities when the Harmony Hub is off. I'm sure others may not want this, so an option would be great.

**Comment by kalhimeo** [comment]
Hi @Snuffy2 , I managed to do what you describe with multiple "harmony-card" and a combination of the "conditional" card (shows if the state of the sensor.harmony_xxx_activity is not 'PowerOff') and the "custom:vertical-stack-in-card" (find on HACS, shows the cards in a vertical stack with no line separation).

Exemple :

```
type: custom:vertical-stack-in-card
cards:
  - type: custom:harmony-card
    entity: remote.xxx
    activities:
      - name: Activity 1
        device: Device x
      - name: Activity 2
        device: Device y
  - type: conditional
    conditions:
      - entity: sensor.harmony_xxx_activity
        state_not: PowerOff
    card:
      type: custom:harmony-card
        entity: remote.xxx
        hide_activities: true
        activities:
          - name: Activity 1
            device: Device x
...
```

Hopes this helps !
