### ISSUE TITLE
can't see custom card after HACS install

### ISSUE THREAD

**Issue by Windyo** [sbryfcz/harmony-card#66]
Seems to be related to #56

**Comment by synth3tk** [comment]
Have you tried making sure it's not indented from the top level?
```
type: custom:harmony-card
entity: [...]
```

instead of

```
- type: custom:harmony-card
  entity: [...]
```

**Comment by evenflow73** [comment]
In the end, anyone who had this issue found a solution?
Feedback would be highly appreciated!

**Comment by espeir** [comment]
> In the end, anyone who had this issue found a solution? Feedback would be highly appreciated!

Below is the config I used for my card.  I haven't actually tested it yet, but the card showed up.  :)
```
type: custom:harmony-card
entity: remote.harmony_hub_lr
volume_entity: media_player.yamaha_receiver_living_room
scale: 1.5
activities:
  - name: Watch Fire TV
    device: Yamaha AV Receiver
  - name: Listen to Music
    device: Yamaha AV Receiver
```
