### ISSUE TITLE
XBox Button Always Visible

### ISSUE THREAD

**Issue by espeir** [sbryfcz/harmony-card#71]
When I add the card to the dashboard, the XBox buttons are always visible.  Nothing in my config mentions XBox...

Card Configuration:
```
type: custom:harmony-card
entity: remote.harmony_hub_lr
volume_entity: media_player.yamaha_receiver_living_room
scale: 1.5
activities:
  - name: Watch Fire TV
    device: Yamaha AV Receiver
  - name: Listen to Music
    device: Yamaha AV Receiver
```

![Screenshot 2022-02-14 163747](https://user-images.githubusercontent.com/65735975/153958597-24441611-e49e-4184-a12c-a9e186e362f5.png)

**Comment by smenzer** [comment]
I agree that this should not be a default button, but you can hide it easily with this at the room of your config:

```yaml
buttons:
  xbox:
    hide: true
```

alternatively, it looks like you can just change the icon and behavior like you can with the other buttons if you want to
