### ISSUE TITLE
Weird issue with middle button on Android

### ISSUE THREAD

**Issue by Dinth** [sbryfcz/harmony-card#87]
Hey. Until recently i have been using a HTPC with Harmony and never had any problems with it. Recently HTPC was replaced with a Nvidia Shield and the middle button (the one in the middle of arrows) stopped working in Harmony Card. This is weird, because in the Harmony app/Harmony remote the middle button is still functioning as expected.

**Comment by Dinth** [comment]
I have kinda resolved it by adding:
```
buttons:
  dpad_center:
    command: Select
    icon: mdi:checkbox-blank-circle
    hide: false
```
to the card configuration, but this is changing behaviour of other activities which were all working fine with defaults
